### ISSUE TITLE
Invalid memory address - org scan - crashing at empty repo

### ISSUE THREAD

**Issue by fr0stedfl4ke** [zricethezav/gitleaks#353]
**Describe the bug**
When running a default scan on our company repo, the scan gets to a certain point where it just crashes. I've identified the repo in question and noticed that it's empty. I'm not sure as to whether this has anything to do with it. The program states that it was unable to clone via https and access tokens, attempts to ssh, unable to get ssh auth, skips, retries cloning the same repo and then crashes.

**To Reproduce**
Run this command ./gitleaks --org=talend --disk --access-token=******** --host=github

**Expected behavior**
The program should have skipped this repo and continued. Instead, it attempted to clone the same repo using git@github:Talend/tps3243_2.git

**Screenshots**
![Screen Shot 2020-03-11 at 10 49 51 AM](https://user-images.githubusercontent.com/42190475/76447519-0cd0cf00-6386-11ea-91dd-2ad430305d65.png)

 - OS: CentOS 7.7-1908
 - Gitleaks Version: 4.1.0

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@fr0stedfl4ke I will be taking a look at this. If a repo is empty there can be some odd behaviors.

**Comment by fr0stedfl4ke** [comment]
@zricethezav Thanks for taking a look into this. Let me know if there's anything else I could do to assist in this process.

**Comment by zricethezav** [comment]
@fr0stedfl4ke just merge https://github.com/zricethezav/gitleaks/pull/358. That should fix it. Could you re-clone and give it a shot? See if that fixes it

**Comment by fr0stedfl4ke** [comment]
@zricethezav Unfortunately, I'm still getting an error with this one - even using the latest version. Any suggestions?
![image](https://user-images.githubusercontent.com/42190475/77333559-d88fd380-6ce0-11ea-9778-2e207965a8e0.png)

**Comment by zricethezav** [comment]
@fr0stedfl4ke I haven't tagged the new release yet as I was planning on putting some more items in before I cut a new release. Could you clone this locally and run it? I'm trying to reproduce it locally but I'm not having success reproducing this bug.

**Comment by GolanTrevize10** [comment]
@zricethezav it works for me as well

**Comment by zricethezav** [comment]
@GolanTrevize10 that's good to hear! I will wait until @fr0stedfl4ke confirms this is working for them before closing out this issue.

**Comment by fr0stedfl4ke** [comment]
Hi @zricethezav, it seems to be crashing once again. Let me know if I did this right

1. git cloned the repo
2. go run main.go with all necessary parameters.

It seems to kick off the program just fine, and then crashes after a certain point. Usually, I run this program using 'screen' and let it run in the background. I can't seem to "scroll" back up on my screen session because I didn't set the proper buffers in place - so that's my fault. I'll try again and check to see where it's crashing on me.

Thanks for the fix. Let me know if I'm running it properly.

**Comment by fr0stedfl4ke** [comment]
@zricethezav - Looks like when I run 'go run main.go' after cloning the repo - it runs out of memory. Even though I use the --disk parameter is seems to have a memory issue. This doesn't happen when I run after go get. Any suggestions? 

![image](https://user-images.githubusercontent.com/42190475/78310677-84b49400-7503-11ea-8a5b-ab85e7bd5bd4.png)

**Comment by fr0stedfl4ke** [comment]
Hi @zricethezav. I went ahead and pulled the latest release and all looks good on my end.

Thank you!
