### ISSUE TITLE
whitelisted repo not whitelisted

### ISSUE THREAD

**Issue by galitz** [zricethezav/gitleaks#377]
Using some config files we ported over from older implementations, we have some repos showing up in reports that we had added to the global whitelist.  

Code snippet:
```
[whitelist]
        description = "Whitelisted things"
        #file = '''(^\.?gitleaks.toml$|(.*?)(jpg|gif|doc|pdf|bin)$)'''
        files = [ '''(?i)translations.json''', '''(?i)keywordtranslation.net.js''' ]

        repos = [
                "internal-api",        ## repo is empty
                "proxy-v2",                 ## repo is archived
                "vagrant",                      ## app has been decommissioned
                "snort-rules",                  ## SEC-8940
        ]

```

`gitleaks --org=security --host=github --baseurl="http://github.redacted" --report=sec-noredact.json --config=tester.toml --disk`

```
[ggalitz@myserver ~]$ grep snort-rules sec-noredact.json | head
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules",
  "repo": "snort-rules"
```

OS: Centos 7
Version: V4 Latest

cc @zricethezav

**Comment by zricethezav** [comment]
That whitelist config was removed in one of the major updates. It makes sense to bring back: https://github.com/zricethezav/gitleaks/pull/378 got a PR open here which will go into the next release.

**Comment by zricethezav** [comment]
fix released in https://github.com/zricethezav/gitleaks/releases/tag/v4.2.0. Reopen this issue if needed.

**Comment by galitz** [comment]
Hi.. alas, it does not seem to be fixed.  I am still seeing results for whitelisted repos.

Here is my test config:

``
[[rules]]
        description = "Generic Credential"
        regex = '''(?i)(api_key|apikey|secret|password|pass|pw|key)(.{0,20})?[0-9a-zA-Z]{16,45}'''
        tags = ["key", "API", "generic"]


[whitelist]
        description = "Whitelisted things"
        repos = [
                "docket",                       ## SEC
        ]

```

**Comment by galitz** [comment]
fyi, I seem to be unable to re-open the issue on my own.

cc @zricethezav

**Comment by zricethezav** [comment]
@galitz my apologies, I did not see you were attempting to whitelist repos using the `host/org` options so the logic to skip whitelisted repos was never hit. Thank you for reopening this. I'm working on a fix right now.

**Comment by galitz** [comment]
Hi.. in doing some further testing it may be that commit hash whitelists are not working?  Should I open a separate issue for that?  Here is my test config file:

´´´
title = "gitleaks config"

[[rules]]
        description = "Generic Credential"
        regex = '''(?i)(api_key|apikey|secret|password|pass|pw|key)(.{0,20})?[0-9a-zA-Z]{16,45}'''
        tags = ["key", "API", "generic"]


[whitelist]
        description = "Whitelisted things"

        commits = [
                "26792e339526c2ac23f31b554085dd3a4e6745a9", # SEC-8940
                "c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952" # SEC-8975 ## tester
        ]

´´´

**Comment by zricethezav** [comment]
@galitz whats your output. This is just a config

**Comment by galitz** [comment]
command line:
´´´
gitleaks --access-token="XXXX" --org=sre --host=github --baseurl="https://github.XXXX.net" --report=sre.json --config="tester.toml" --redact
´´´


´´´
[ggalitz@ops-security_scanner01.us-east-1 ~]$ more tester.toml
title = "gitleaks config"

[[rules]]
	description = "Generic Credential"
	regex = '''(?i)(api_key|apikey|secret|password|pass|pw|key)(.{0,20})?[0-9a-zA-Z]{16,45}'''
	tags = ["key", "API", "generic"]


[whitelist]
	description = "Whitelisted things"

        commits = [
                "3237181d85bc1dfb79f3b6ef144d21cfe62fb992", # SEC-8974
                "4cac1c3845435dc9cf69ac87fdc89164c73b8598", # SEC-8975
                "c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952", # SEC-8975 ## tester
        ]


[ggalitz@ops-security_scanner01.us-east-1 ~]$ grep c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952 sre.json
  "commit": "c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952",
  "commit": "c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952",
  "commit": "c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952",
  "commit": "c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952",
  "commit": "c85147ca95ae0dcc4f7cd8ddee2efa4f61cb1952",

´´´

**Comment by zricethezav** [comment]
@galitz I'm not supporting github/gitlab apis anymore so this issue won't be fixed. See https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0
